global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'clayen-dev'
    scrape_interval: 10s
    static_configs:
      - targets:
          - grafana.clayen.dev:9100

  - job_name: 'itam-edu-dev'
    scrape_interval: 5s
    static_configs:
      - targets:
        - edu.itam.clayen.dev:9100
        - livekit.edu.itam.clayen.dev:9100
